export const CREDIT_RULES = {
  INITIAL_CREDITS: 5,
  CREDITS_PER_SWAP: 2,
  TEACHING_REWARD: 2,
  MIN_SESSION_DURATION_MINS: 15,
  MAX_SESSION_DURATION_MINS: 180,
  CANCELLATION_POLICY: {
    FULL_REFUND_BEFORE_SESSION: true,
    ALLOW_PARTIAL_AFTER_START: false,
  },
  MIGRATION_VERSION: 1,
} as const;
